### PR TITLE
Solver

### PR DESCRIPTION
**Pull request by Trebor-Huang**
I wrote a test case. The syntax can probably be made better (avoiding those little `ᶠ`s).

Without univalence across levels, we still need to either start out with `Bool→Type*` everywhere (which requires a new set of lemmas not in standard library), or prove that `Γ ⊢ F` respects isomorphism.

### CODE REVIEW

**Comment by Trebor-Huang** [comment]
I think I can come up with a better syntax, testing...

**Comment by Trebor-Huang** [comment]
I'll call that a day.

Two ways we can improve that:
- Use currying to avoid `FinVec` and `Fin`. See [here](https://github.com/Trebor-Huang/ZFC/blob/17c170aeaff738d0b3d2063e4dee680d321467d5/logic.agda#L392-L482).
- Use tactic to read the type from the hole. I think this does more harm than good.
  - It requires explicit type signature anyway, so if you use it in the middle of a proof you're lost.
  - It is also unpredictable, because `×` is encoded as `∑`s, it can't tell if some `∑` should be taken as conjunctions (without nontrivial tests).
  - It is slow. It needs to tell if two expressions are the same, so that it will count them as the same proposition during solving. This means it needs to compare pairs of expressions by normalizing.

**Comment by Trebor-Huang** [comment]
I think you can change some symbols like `∧ᶠ` and `⅋` to whatever you like. I'm too tired to come up with good ones.

**Comment by kangrongji** [comment]
Great work already! Leave the further plan for future.

**Pull request merged**
