### PR TITLE
Boolean Solver

### PR DESCRIPTION
**Pull request by Trebor-Huang**

### CODE REVIEW

**Comment by Trebor-Huang** [comment]
A few questions on style:

- Should I use `with` clauses or use `case_blah_blah_`?
- What is the most convenient use case? `Bool` or `Type` (carrying `Dec P` around) or `DecProp`?
- Do we need metaprogramming? (This sometimes saves you from having to write a type signature twice.)

**Comment by Trebor-Huang** [comment]
Side note: I am using cubical commit agda/cubical@1b9c97a2140fe96fe636f4c66beedfd7b8096e8f

**Comment by Trebor-Huang** [comment]
There is already a `isPropIsDecProp` in agda/cubical@1b9c97a. I didn't bother to track them down, can you take a look?

**Comment by kangrongji** [comment]
Don't bother with the other one. The definition in use is more standard.

**Pull request merged**
